### 取り組んだ課題
 - JavaScript Primer - 迷わないための入門書

### 学んだこと

### 例外処理

- throw文
任意の場所で例外を発生させる。
```
try {
  throw new Error("エラーが発生しました");
} catch (error) {
  console.llog(error.message);　// "エラーが発生しました"
}
```
- console.error  
console.log()と使い方は同じで、ブラウザでエラーのログが確認できる。
デバックで使用すると良さそう。

- causeオプション  
Errorオブジェクトの`cause`オプションを使用すると別エラーのスタックトレースが引き継げる。

### 非同期処理(Promise)

Promiseは非同期処理を扱うビルトインオブジェクト

```
const promise = Promise.resolve();
promise.then(() => {
    console.log("コールバック関数が実行されました");
});
console.log("同期的な処理が実行されました");
```

```
Promise.resolve(2).then((value) => {
    return value * 2;
}).then(value => {
    console.log(value); // => 4
    return value * 2;
}).then(value => {
    console.log(value); // => 8
}).then(value => {
    // ↑でreturnしていないため、「undefined」が返される。
    console.log(value); // => undefined
});
```

- Promise.all  
複数のPromise処理を一つのPromiseとして扱える。  
全てのPromiseの処理が終わるまで待つ。

```
function fn(num) { return num };

const promise1 = fn(1);
const promise2 = fn(2);
const promise3 = fn(3);

Promise.all([promise1, promise2, promise3]).then(function(values) {
    console.log(values); // => [1, 2, 3]
});
```

- Promise.race  
複数のPromise処理を一つのPromiseとして扱える。  
一番最初に処理が完了した（競争させる: race）Promiseに対して処理がされる。

### 非同期処理(Async Function)

- 必ず`Promiseインスタンス`を返す。
- `await`式が利用できる。

```
async function returnText() {
    return "this function is async"
};

returnText().then(value => {
    console.log(value); // "this function is async"
})
```

### 明日やること
- JavaScript Primer - 迷わないための入門書

### 感じたこと
- もう少しで1部完了する
- ところどころで長い章があるので集中が切れる時がある

### 学習時間
- 2h